version: '3.9'

services:
  postgres:
    image: postgres:10.3
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: online-chat
      POSTGRES_USER: "doo-dev"
      POSTGRES_PASSWORD: "123456"